addition of contributor jpuple
osscameroon/osscameroon-blog pull request #45
Opened 2021-12-13 19:27 UTC by J-Purple

2021-12-14 11:39 UTC, RMPR commented
Minor nitpick, there's a typo in your commit message
> jpuple

2021-12-14 11:40 UTC, RMPR requested changes

2021-12-14 11:40 UTC, RMPR commented on content/post/contributors/jpurple.md
> +Hi there, I'm Ngnepedoh Irving Craig( yh but call me purple/jpurple ), young aspiring developper. I am an IT enthusiast and am fascinated by Artificial Intelligence. I am familiar with Java, Python a
```suggestion
Hi there, I'm Ngnepedoh Irving Craig (yh but call me purple/jpurple), young aspiring developer. I am an IT enthusiast and am fascinated by Artificial Intelligence. I am familiar with Java, Python and C. Currently working as an android app developer. I look forward to working with you all and am excited about what I will learn here.
```

2021-12-15 19:22 UTC, J-Purple commented
oh thanks, just committed the changes...

2021-12-15 22:02 UTC, elhmn approved these changes

2021-12-22 09:39 UTC, RMPR approved these changes

2021-12-22 09:44 UTC, merged

2021-12-22 09:45 UTC, RMPR commented
@elhmn you can add yotas to this one as well