Add new article Music and silence in coding
osscameroon/osscameroon-blog pull request #46
Opened 2021-12-14 01:05 UTC by SHABA-Rex

Hello everyone, thank you in advance for your verification.

2021-12-22 09:38 UTC, RMPR requested changes

2021-12-22 09:38 UTC, RMPR commented on content/post/articles/Music-and-silence.md
> +Lao Tzu said <<*Silence is a source of Great Strength*>>
I don't think this quote fits the whole point of this section. Not only [it's not directly from Lao Tzu](https://www.taoistic.com/fake-laotzu-quotes/fake-laotzu-quote-Silence_is_a_source_of_great_strength.htm) but where it's coming from, (The Tao of Leadership: Lao Tzu's Tao Te Ching Adapted for a New Age from 1985, by John Heider), where the author allowed himself considerable deviations from the original. If we quote including the 4 lines before the excerpt you took:

> The leader does not gossip about others or waste breath arguing the merits of competing theories.
Silence is a great source of strength.

Here silence is not meant for silence around you, rather silence from you (or in you as you wish), so I don't think it's really applicable in this specific case.

2021-12-22 09:38 UTC, RMPR commented on content/post/articles/Music-and-silence.md
> +Not everyone uses music to cope with the different difficulties that one can encounter while coding so there are those who are for silence (the zone), a 2013 [study](https://www.researchgate.net/publ
```suggestion
Not everyone uses music to cope with the different difficulties that one can encounter while coding so there are those who are for silence (the zone), a 2013 [study](https://www.researchgate.net/publication/259110014_Is_silence_golden_Effects_of_auditory_stimuli_and_their_absence_on_adult_hippocampal_neurogenesis) found that two hours of silence could create new cells in the hippocampus region, a brain area linked to learning, remembering and emotions. According to a 2006 [study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1860846/), two minutes of silence relieves tension in the body and brain and is more relaxing than listening to music.  
```

You should mention that this [study](https://www.researchgate.net/publication/259110014_Is_silence_golden_Effects_of_auditory_stimuli_and_their_absence_on_adult_hippocampal_neurogenesis) was conducted on mice, and the type of music involved is again, classical music. 

And this:
> [study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1860846/), two minutes of silence relieves tension in the body and brain and is more relaxing than listening to music.  

Doesn't paint the complete picture, the articles specifically states that two minutes of silence *between* two music listening session is what causes relaxation. There are no mention of silence alone. So this is more an argument for both music and silence, with no clear cut.

2021-12-22 09:38 UTC, RMPR commented on content/post/articles/Music-and-silence.md
> +When you allow thoughts to go where they want, inspiration can flow. Solutions to current or long standing problems may suddenly appear to you, or a workaround or innovative approach may seem more ac
A so-called scientific website with ads all over the place makes me question his legitimacy, moreover it starts with the quote:

> “Silence is a source of great strength.” – Lao Tzu

That we already established is not from Lao Tzu. It makes me question how deep they went in their research. Nonetheless, to their credit, they say:

> Silence may help in the following areas

"may" is a keyword here, that means it's possible, not for sure, but possible. Moreover, nowhere in the article they talk about silence during coding. There, silence is more associated to a break, which is another subject by its own.

2021-12-22 09:38 UTC, RMPR commented on content/post/articles/Music-and-silence.md
> +When you practice solitude and silence, you allow your brain to process your emotions, rather than suppressing them and staying on autopilot. You may experience uncomfortable emotions during this pro
Now I am a bit confused, the title is "Music and silence *in coding* " why are you talking of the "practice of solitude and silence"? What you're saying here is not directly related (if at all) to coding, or at least, I am not able to see it.

2021-12-22 09:38 UTC, RMPR commented on content/post/articles/Music-and-silence.md
> +Thanks for reading. Here are my sources:
Mentioning articles you already linked in the body of the article is a bit redundant, don't you think?

2022-01-16 01:07 UTC, SHABA-Rex commented on content/post/articles/Music-and-silence.md
> +Opinions are divided on the subject, on the one hand we have coders who like to boost their concentration and productivity by listening to music and those who only want "silence"👄, in this article we
Hello, thank you for your review.
I put the emojis to give more emotions to my words, to make them a little more visual , and i think is important to visualise while reading the article.
My editor didn't have this emoji, thanks to you, I'll be able to copy the one you put in your comment. :) 
Please do you know how to put this emoji 🤫 on sublime text without copying it on something?

2022-01-16 03:55 UTC, SHABA-Rex commented on content/post/articles/Music-and-silence.md
> +The brain has to make efforts to analyze and process information based on abstract and logical reasoning during coding, several studies such as [University of Birmingham research](http://www.scienced
In this paragraph, my objective was to state that music has a good impact on our brain activity when coding regardless of the type of music or the way of coding and to show that this impact would improve concentration and productivity. I agree with you that the studies chosen were not appropriate to support this view.
I will replace those studies by a good one.

2022-01-24 02:41 UTC, closed without merging