added velda as contributor
osscameroon/osscameroon-blog pull request #72
Opened 2022-02-23 18:00 UTC by Mankavelda

2022-02-23 18:24 UTC, Sanix-Darker requested changes

2022-02-23 18:24 UTC, Sanix-Darker commented on content/post/contributors/manka-velda.md
> +Hi, I'm Manka Velda 😄, an aspiring computer engineer. I'am interested in web development and graphic design. I just started my journey in pthon and I feel being in love 💓 with that stuff!
*in python

2022-02-26 21:13 UTC, RMPR commented on content/post/contributors/manka-velda.md
> +Hi, I'm Manka Velda 😄, an aspiring computer engineer. I'am interested in web development and graphic design. I just started my journey in python and I feel being in love 💓 with that stuff!
```suggestion
Hi, I'm Manka Velda 😄, an aspiring computer engineer. I am interested in web development and graphic design. I just started my journey in Python and I feel being in love 💓 with that stuff!
```

2022-03-01 11:25 UTC, elhmn approved these changes

2022-03-01 11:25 UTC, merged